name:                elab
version:             0.1.0.0
github:              "Trebor-Huang/elab"
license:             BSD-3-Clause
author:              "Trebor Huang"
maintainer:          "treborhuang@foxmail.com"
copyright:           "2025 Trebor Huang"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Trebor-Huang/elab#readme>

dependencies:
- base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

default-extensions:
  DeriveGeneric
  MultiParamTypeClasses
  LambdaCase
  BlockArguments
  FlexibleContexts
  FlexibleInstances
  OverloadedStrings
  PatternSynonyms

library:
  source-dirs: src
  dependencies:
    - unbound-generics >= 0.4.4
    - mtl >= 2.3.0
    - megaparsec >= 9.7.0
    # - parser-combinators >= 1.3.0
    - lens >= 5.3.0
    - containers >= 0.7

executables:
  elab-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elab
    - unbound-generics >= 0.4.4

tests:
  elab-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - elab
    - unbound-generics >= 0.4.4
    - hspec
